### ISSUE TITLE
why source code in libs?

### ISSUE THREAD

**Issue by joeaudette** [Maarten88/rrod#1]
Hi Maarten, 
Thanks for sharing your work! 

I've been working with asp.net core for a while, but very interested in learning orleans, react, redux stack.

In studying the code in this solution, was wondering why the lib folder has source code for things like MailKit/MimeKit/BouncyCastle when there exist .net core compatible nugets for those things?

Thanks,

Joe

**Comment by Maarten88** [comment]
I did that because when I wrote this code (in the project.json days) I had several problems getting those dependencies and versions working right (resulting in Assembly Load Exceptions) when using the original NuGet versions.
For instance, some packages use (the old) RxMain dependency while others have (the new) System.Reactive: if you get both of these in the dependency tree they will conflict.

I sometimes also did this to be able to be able to debug into external code, and was just lazy to revert back after I solved the problem.

I think that these problems have mostly resolved themselves now with updated versions of packages, the current Dotnet Core project system and vs 2017. You could try to replace the source versions in lib with the nuget versions of these dependencies. There is no changed functionality in them, I only modified the project files.

**Comment by joeaudette** [comment]
Thanks for your prompt response. Are you considering changing back to the nugets in this solution example? If I fork it and get it working with the nugets would you accept a pull request?

**Comment by Maarten88** [comment]
Yes, I'd certainly accept a pull request if you get it working.

**Comment by Maarten88** [comment]
I recently updated all dependencies to new versions, and removed all the cloned code in the lib folder in exchange for the respective builds from nuget.
