### ISSUE TITLE
Constructor Errors with Footer.tsx, Login.tsx, and scroll-effect.tsx

### ISSUE THREAD

**Issue by BillHertzing** [Maarten88/rrod#10]
Thanks for putting this project together. It looks like a great way for me to learn more about each of these technologies. Having problems getting it to run, though.  Getting the following error in the constructor for the components footer, login, and scroll-effect .tsx files. Details shown in attached screenshot image.

Error	TS2554	(TS) Expected 1-2 arguments, but got 0.	Webapp (tsconfig project)	

Also have those errors as shown in the screenshoton the HOCBBaseRender.tsx file, looks like the .tsx file  expects React to have a default export, but React ( at least the version being used by this project in my environment) does not....

![image](https://user-images.githubusercontent.com/894644/34436828-59ad3946-ec67-11e7-9a16-51e92adec230.png)

Would appreciate your insights on how to correct these issues.

Developing on Windows 10 Pro, Visual Studio 2017 V15.5.2, Node V8.9.3, npm 5.6.0

**Comment by Maarten88** [comment]
I'm not sure why you get these errors, when I run webpack on the command line the .ts components compile without problems. HOCBaseRenderer is not even used anymore.

Personably I disable typescript compilation errors when working in VS, it gives me too many problems because VS creates its own typescript environment, does not really respect tsconfig etc. Just run the solution as documented and ignore the VS messages.

I think by adding props as the constructor argument this warning should go, so I made that change. I deleted the unused HOCBaseRenderer component. Does this update work for you?
