### ISSUE TITLE
Very impressive

### ISSUE THREAD

**Issue by ensemblebd** [Maarten88/rrod#11]
This was hard to find. But am glad I did. 
Thank you for the extensive and impressive effort on this project. 

Planning to try it out for an internal only employee application, will contribute if necessary, but mostly wanted to express my thanks!

**Comment by Maarten88** [comment]
Thanks for the compliment! I welcome contributions.

Be advised that there seems to be a new bug in the SignalR connection/subscription, caused by recent changes in the framework. I'll try to find and fix that.

Also, for an employee-only application, you may not need the serverside rendering features of this project: it adds complexity, mainly for the purpose of SEO, that you probably don't need.
