### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by pkkr** [Maarten88/rrod#2]
Hey there, thanks for your blog posts. I wanted to try out your project but havin some trouble to set it up.
I keep getting errors that node --debug is deprecated and your Dockerfile ist missing the project.json file.. apparently this file is depereacted too...
Can you please tell what to do with the current .net Core and Node Version ?

**Comment by Maarten88** [comment]
I think the dockerfile came with an early version of the JavascriptServices template project; I did not use and maintain it; sorry. I deploy using Yams myself and know very little about docker.

In general, project.json was replaced by respective .csproj files in each project. The node --debug is started that way by aspnet javascriptservices, if you'd change https://github.com/Maarten88/rrod/blob/master/src/Webapp/Program.cs#L253-L254 then the warning would probably go away (but you'd also be unable to debug serverside javascript).

The Javascript services templates have removed the dockerfile, but there is an discussion about it [here](https://github.com/aspnet/JavaScriptServices/issues/763).
There is another discussion about using docker with orleans [here](https://github.com/dotnet/orleans/issues/2571), maybe those can help you.

**Comment by pkkr** [comment]
Sorry for my late reply and thaks for your response.
I still cant get your example to run. Which Version of .NET Core did u use ? 

These are the errors i get:
![fehler1](https://user-images.githubusercontent.com/1502899/27256676-92b65b98-53bd-11e7-9dab-b5574e438ad5.PNG)

and in the Browser
![fehler2](https://user-images.githubusercontent.com/1502899/27256678-9db761b8-53bd-11e7-8f1e-2eddd43a9860.PNG)

any idea ?

**Comment by Maarten88** [comment]
[Disable nodejs debugging](https://github.com/Maarten88/rrod/commit/b936368fe5747da180f3a77f3b2cf815a09c7707) and try again. This JavascriptServices feature is broken with new nodejs versions and it seems this won't be fixed for dotnet core 1.x (https://github.com/aspnet/JavaScriptServices/issues/995)

There are also 3 typescript compiler errors. To see them, run 'webpack' in the Webapp folder. Maybe those are fixed in this [update](https://github.com/Maarten88/rrod/commit/6d2466da1ec60c76a49cdfa730fcb440513b06aa) from today.
